services:
  calendar:
    image: calendar
    container_name: calendar
    build: ./calendar/
#    depends_on:
#      db:
#        condition: service_healthy
#      migrations:
#          condition: service_completed_successfully
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=calendar
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s

  migrations:
    image: migrations
    build: ./calendar/migrations/
    container_name: migration
    depends_on:
      - db